# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - development

pool:
  vmImage: 'windows-2022'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  name: 'OperationsUnitTest'
  displayName: 'Run tests'
  inputs:
    command: 'test'