# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - development

jobs:
- job: Build
  pool:
    vmImage: 'windows-2022'

  variables:
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    solution: '**/*.sln'
    project: '**/*.csproj'

  steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    name: 'OperationsUnitTest'
    displayName: 'Run tests'
    inputs:
      command: 'test'
      projects: '$(solution)'
      arguments: '--configuration $(BuildConfiguration)'    

- job: Publish
  steps:
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'C:\Users\oli\source\repos\test-repo\Calculator\bin\Debug\net6.0'
      ArtifactName: 'calc'

##[warning]Directory '/home/vsts/work/1/a' is empty. Nothing will be added to build artifact 'calc'.