# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - development

jobs:
- job: Build
  pool:
    vmImage: 'windows-2022'

  variables:
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    solution: '**/*.sln'
    project: '**/*.csproj'

  steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    name: 'OperationsUnitTest'
    displayName: 'Run tests'
    inputs:
      command: 'test'
      projects: '$(solution)'
      arguments: '--configuration $(BuildConfiguration)'    

- job: Deploy
  steps:
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'calc'
      publishLocation: 'Container'