# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - development

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**\Calculator.Calculator.sln'
  project: '**\Calculator.Calculator.csproj'

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
