# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - development

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projects: '$(Parameters.projects)'

steps:
- task: DotNetCoreCLI@2
  name: 'OperationsUnitTest'
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
